apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
  namespace: default #edit the namespace if needed      
spec:
  type: LoadBalancer      
  selector:
    app: nginx            
  ports:
    - protocol: TCP
      port: 80            
      targetPort: 80      
